---
title: "proj2"
author: "pj"
date: "2022/10/17"
output: pdf_document
---
#1
```{r , include=FALSE}
pone=function(n,k,strategy,nreps){
  boxes=1:(2*n)
  successes=0
  if(strategy==1){
    for (i in 1:nreps){
      cards=sample(2*n,2*n)
      successes=successes+core_while(n,1,k,cards)
    }
      prob=successes/nreps
      return(prob)
    
  }
  if(strategy==2){
     for (i in 1:nreps){
      cards=sample(2*n,2*n)
      successes=successes+core_while(n,0,k,cards)
    }
    prob=successes/nreps
    return(prob)
    
 }
  if(strategy==3){
     for (i in 1:nreps){
      cards=sample(2*n,2*n)
      opened_boxes=sample(2*n,n)
      if(any(opened_boxes==k)==TRUE)
        successes=successes+1
    }
    prob=successes/nreps
    return(prob)
  }
}
```

```{r}
core_while=function(n,attemptss,p,cards)
  {
    success=0
    if (attempts==1)
   {
     card_num=cards[p]
    }
    
   if (attempts==0)
   {
     card_num=sample(cards,1)
     attempts=1
   }

    while(attempts<n)
    {
     
      if(card_num==p)
      {
        success=1
        break;
      }
      else
      {
        card_num=cards[card_num]
      }
      attempts=attempts+1
    }
    return(success)
}
```

## 2

```{r 2}
pall=function(n,strategy,nreps)
  {
  prisoners=1:(2*n)
  all_released=nreps
  if(strategy==1){
    for (i in 1:nreps){
      cards=sample(1:(2*n),2*n)
      for (prisoner in prisoners)
      {
        if(core_while(n,1,prisoner,cards)==0)
        {
          all_released=all_released-1
          break
        }
      }
    }
    return(all_released/nreps)
  }
  if(strategy==2){
    for (i in 1:nreps)
    {
      cards=sample(1:(2*n),2*n)
      for (prisoner in prisoners)
      {
        if(core_while(n,0,prisoner,cards)==0)
        {
          all_released=all_released-1
          break;
        }
      }
    }
    return(all_released/nreps)
    
  }
  if (strategy==3)
  {
    for (i in 1:nreps)
    {
      cards=sample(1:(2*n),2*n)
      for (prisoner in prisoners)
      {
        opened_boxes=sample(1:(2*n),n)
        if (any(opened_boxes==prisoner)==FALSE)
        {
          all_released=all_released-1
          break;
        }
      }
    }
    return(all_released/nreps)
  }
}
```
##3
```{r}
#Individual success probability
#n=5
#strategy 1
pone(5,3,1,10000)
#strategy 2
pone(5,3,2,10000)
#strategy 3
pone(5,3,3,10000)
#n=50
#strategy 1
pone(50,3,1,10000)
#strategy 2
pone(50,3,2,10000)
#strategy 3
pone(50,3,3,10000)
#Joint success probability
#n=5
#strategy 1
pall(5,1,10000)
#strategy 2
pall(5,2,10000)
#strategy 3
pall(5,3,10000)
#n=50
#strategy 1
pall(50,1,10000)
#strategy 2
pall(50,2,10000)
#strategy 3
pall(50,3,10000)
```

## 5 dloop
```{r ,echo=FALSE}
dloop=function(n,nreps)
{
  boxes=1:(2*n)
  occurence=rep(0,2*n)
  for (i in 1:nreps)
  {
    occurence_time=rep(0,2*n) 
    cards=sample(boxes,2*n)
     depth=1
     u=cards
     permutation_matrix=cards
     while(depth<2*n)
     {
      u=cards[u]
      permutation_matrix=rbind(permutation_matrix,u)
      depth=depth+1
     }
     for (box in boxes)
     {
       occurence_time[which(permutation_matrix[,box]==box)[1]]=1
     }
    occurence=occurence+occurence_time
  }
  probs=occurence/nreps
  return(probs)
}
```

# 6
```{r, echo=FALSE}
n=50 
nreps=10000
prob=dloop(n,nreps)
prob
```

```{r}
dloop.check=function(n,nreps)
{
  boxes=1:(2*n)
  less_50=0
  for (i in 1:nreps)
  {
     cards=sample(boxes,2*n)
     depth_measure=rep(0,2*n)
     depth=1
     u=cards
     permutation_matrix=cards
     while(depth<2*n)
     {
      u=cards[u]
      permutation_matrix=rbind(permutation_matrix,u)
      depth=depth+1
     }
     for (box in boxes)
     {
      depth_measure[which(permutation_matrix[,box]==box)[1]]=1
     }
      if (any(depth_measure[(n+1):(2*n)]==1)==FALSE)
      {
        less_50=less_50+1
      }
    }
  return(less_50/nreps)
}
```

```{r}
d=1:100
plot(d,prob,type='b',col=4,xlab='loop depth',ylab='probability',main='probability of occurence for loops in depth 1 to 100')

```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
